### ISSUE TITLE
Need to point to parent package to get tests picked up

### ISSUE THREAD

**Issue by htgoebel** [nicoddemus/pytest-drop-dup-tests#3]
Follow up to https://mail.python.org/pipermail/pytest-dev/2020-January/004895.html:

If drop-dup-tests is used:
=> When pointing pytest to the package containing the tests, they will NOT be picked up
=> When pointing pytest to the parent package the tests will be picked up

@nicoddemus  managed to reproduce the issue but only after installing the exact same versions of pytest, pluggy, and plugins. 

platform linux -- Python 3.7.5, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
plugins: cov-2.7.1, drop-dup-tests-0.1.0, forked-1.0.2, timeout-1.3.3, xdist-1.29.0

My package layout follows the "Tests as part of application code, with `__pyinstaller` containing the tests to be picked up.

The repo <https://github.com/htgoebel/hooksample-for-pytest-bug> contains two branches:

1. "one-level-less": test-cases are in `src/pyi_hooksample/__pyinstaller`

     `pytest src/pyi_hooksample/__pyinstaller`
     -> NO tests will be picked up

2. "master": test-cases are in `src/pyi_hooksample/__pyinstaller/t` (mind the trailing `/t`)

   `pytest src/pyi_hooksample/__pyinstaller/t`
   -> NO tests will be picked up

   `pytest src/pyi_hooksample/__pyinstaller   # one level above the test`
   -> tests will be picked up

**Comment by nicoddemus** [comment]
Thanks @htgoebel!

I will try to find some time to take a close look at this, but meanwhile if anybody wants to take a look I suspect it is not a hard fix.

**Comment by htgoebel** [comment]
Another combination that failed to pick up the tests:
platform linux -- Python 3.7.1, pytest-4.3.1, py-1.7.0, pluggy-0.13.1
plugins: timeout-1.3.4, forked-1.1.3, xdist-1.31.0
See https://travis-ci.org/pyinstaller/hooksample/jobs/638052943
Maybe it's not drop-dup-tests.

**Comment by nicoddemus** [comment]
Strange... did you manage to reproduce this locally? 

I've followed the same steps as Travis and things work for me:

```
λ python -m PyInstaller.utils.run_tests
======================== test session starts ========================
platform win32 -- Python 3.7.4, pytest-4.3.1, py-1.7.0, pluggy-0.13.1
rootdir: C:\Users\bruno\hooksample, inifile:
plugins: forked-1.1.3, timeout-1.3.4, xdist-1.31.0
collected 1 item

..\.env37\lib\site-packages\pyi_hooksample\__pyinstaller\test_hooksample_packaging.py . [100%]

===================== 1 passed in 5.30 seconds ======================
```

(Windows though, although I doubt it would produce different results)

**Comment by htgoebel** [comment]
Curiously locally it worked. I will change the calling code a bit to show which paths are actually passed to pytest

**Comment by nicoddemus** [comment]
Sounds good

**Comment by htgoebel** [comment]
Okay, here it is: https://github.com/pyinstaller/hooksample master now contains [two CI tests](https://github.com/pyinstaller/hooksample/blob/master/.travis.yml#L53) showing that is works when drop-dup-tests is not installed (first case) but fails when drop-dup-tests is installed (second case).
  Build outputs can be found at https://travis-ci.org/pyinstaller/hooksample/builds/638152487, build #23.5 and 23.6.

**Please note the changed repo!**

These test-cases use a patched version of the PyInstaller in-development version which is to be tested: 1) Entrypoints for hooks and test-cases have been removed, so this package can be installed. 2) Arguments passed to pytest.run() are printed first.

**Comment by nicoddemus** [comment]
Found the underlying problem, thanks! I will prepare a new release soon. 😁
